# Generated by Django 3.2.5 on 2022-01-25 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200, null=True)),
                ('endereco', models.CharField(max_length=200, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('grupo', models.CharField(choices=[('Casa', 'Casa'), ('Apartamento', 'Apartamento'), ('Terreno', 'Terreno')], max_length=20, null=True)),
                ('tipo', models.CharField(choices=[('Proprietario', 'Proprietário'), ('Construtora', 'Construtora'), ('Leilao', 'Leilão')], max_length=20, null=True)),
            ],
        ),
    ]
